### ISSUE TITLE
Not displaying error modal from back-end

### ISSUE THREAD

**Issue by prawich-th** [Alt-Developers/CentralAuthentication#2]
When back-end return error with the error the modal did not displayed 
<img width="646" alt="Screen Shot 2565-05-05 at 13 44 47" src="https://user-images.githubusercontent.com/90727258/166874251-77a01134-3623-4c67-9402-15c7f91c2fe1.png">

as you can see the modal is true but the modal did not display and just redirect to the login page.
the problem is the user did not get created but there's no visual indication of it when the user try to login, it will say user not found.

this lead to some user cannot use SS' products especially Timetables.
this issue is urgent and need to be resolve as soon as possible.

<img width="1440" alt="Screen Shot 2565-05-05 at 13 41 09" src="https://user-images.githubusercontent.com/90727258/166874145-f09ac449-0e90-48bd-b802-1a7688d814fe.png">

**Comment by Jiraties** [comment]
This bug has been fixed now, but please look into this [security flaw]( https://github.com/SS-Developers/SS-APIs/issues/4) first. Until this security flaw hasnt been fixed, the bug refered to in this issue will not be launched into production.

**Comment by Jiraties** [comment]
Issue has be resolved and been launched into production
